#!/bin/bash
# please do not edit this file or change filename
docker run -it --network host --privileged     --name hb_deploy     --env RMW_IMPLEMENTATION=rmw_fastrtps_cpp     --env ROS_DOMAIN_ID=70     --user 1000:1000     --volume /dev/:/dev/     --volume /home/hb/hb_ws:/home/hb/hb_ws     macnack/hb_deploy:humble bash
