#!/usr/bin/env bash

set -e
mkdir -p /home/${USER}/.ros/mab/config

if [ -f /home/${USER}/${WORKSPACE}/install/setup.bash ]; then
    echo "source /home/${USER}/${WORKSPACE}/install/setup.bash" >> /home/${USER}/.bashrc;
fi

if [ ! -f .ros/mab/config/global.json ]; then
    if [ -f /home/${USER}/${WORKSPACE}/src/hb40/src/hb40_commons/config/global.json ]; then
        cp /home/${USER}/${WORKSPACE}/src/hb40/src/hb40_commons/config/global.json /home/${USER}/.ros/mab/config/global.json
    fi
fi
echo 'Startup completed.'
exec "$@"
